src/pages/Projects/ProjectDetail/ProjectDetail.stories.tsx, src/pages/Projects/ProjectDetail/ProjectDetail.test.tsx, src/pages/Projects/ProjectDetail/ProjectDetail.tsx, src/pages/Projects/Projects/components/ProjectsHeader/ProjectsHeader.tsx, src/pages/Projects/components/ProjectDeleteButton/ProjectDeleteButton.tsx, src/pages/Projects/components/ProjectDescription/ProjectDescription.test.tsx, src/pages/Projects/components/ProjectDescription/ProjectDescription.tsx
**Before**
**After**
**Loading Skeleton**
**Matching Figma**
=> STAF-61 - Project Page: Empty Roles

src/pages/Employees/components/EmployeeModal/EmployeeModal.tsx
=> Removed the two word name requirement for EmployeeModal

src/pages/Employees/Employees.test.tsx, src/pages/Employees/Employees.tsx, src/pages/Projects/Projects/components/ProjectsHeader/ProjectsHeader.test.tsx, src/pages/Projects/Projects/components/ProjectsHeader/ProjectsHeader.tsx
[STAF-132](https://bitovi.atlassian.net/browse/STAF-132)
Uses chakra `<Heading>` tags as `<h1>`'s. Includes tests that check the dom element.
=> Switch <Text> to <Heading>

src/pages/Employees/Employees.tsx, src/pages/Employees/components/EmployeesBreadcrumbs/EmployeesBreadcrumbs.tsx, src/pages/Employees/components/EmployeesBreadcrumbs/index.tsx
fix the flickering that happens when the page is loading
=> STAF-80: show breadcrumbs when page is loading

src/pages/Employees/components/EmployeeModal/EmployeeModal.test.tsx, src/pages/Employees/components/EmployeeModal/EmployeeModal.tsx, src/pages/Employees/components/EmployeeTable/EmployeeTable.tsx, src/services/api/Employees/Employees.ts
=> STAF-162: Update employee works against service layer

src/pages/Employees/Employees.test.tsx
There is a ticket to investigate the issue and fix the test. Skipping
it for the time being so it does not block the automatic deployment
of newer PRs.
Ticket: https://bitovi.atlassian.net/browse/STAF-217
=> Skip create employee test breaking the build

src/mocks/baseMocks/requestCreator.ts, src/pages/Dashboard/Dashboard.test.tsx, src/pages/Dashboard/Dashboard.tsx, src/pages/Dashboard/components/ReportTable/ReportTable.tsx, src/pages/Dashboard/components/ReportTable/TableHeader/TableHeader.stories.tsx, src/pages/Projects/components/DeleteRoleModal/DeleteRoleModal.tsx, src/services/projection/projections/projections.ts, src/services/projection/useProjection.ts
Loaded skills with useSkills hook and passed them to the reportTable component to display them. I kept the projections numbers as random
=> Staf-81: list actual skills in dashboard

src/mocks/baseMocks/requestCreator.ts, src/pages/Projects/ProjectDetail/ProjectDetail.tsx, src/pages/Projects/components/DeleteRoleModal/DeleteRoleModal.test.tsx, src/pages/Projects/components/DeleteRoleModal/DeleteRoleModal.tsx, src/pages/Projects/components/RoleList/RoleList.tsx, src/pages/Projects/components/RoleModal/RoleModal.tsx, src/services/api/Roles/Roles.ts, src/services/api/restBuilder/restBuilder.ts
enable relationships for cache mutations -> changes in restBuilder with the mutateParentCache function
fix roles in mock layer -> rollback useRoles fetching and requestCreator fix
show identifier in toasts -> add identifier parameter in rest mutations
=> Various fixes for roles + enable relationships for cache mutations

src/pages/Projects/ProjectDetail/ProjectDetail.tsx, src/pages/Projects/components/RoleCard/RoleCard.tsx, src/pages/Projects/components/RoleList/RoleList.tsx, src/pages/Projects/components/RoleModal/RoleModal.module.css, src/pages/Projects/components/RoleModal/RoleModal.stories.tsx, src/pages/Projects/components/RoleModal/RoleModal.test.tsx, src/pages/Projects/components/RoleModal/RoleModal.tsx, src/services/api/Assignments/Assignments.ts, src/services/api/Roles/Roles.ts
https://user-images.githubusercontent.com/13068398/158897664-dae0c0bf-807c-4527-89f9-b1efb40a5f51.mov
=> staf-68: add,update,delete assignments in role edit mode

src/App/components/Layout/Layout.tsx, src/components/Badge/Badge.tsx, src/mocks/baseMocks/requestCreator.ts, src/pages/Dashboard/Dashboard.tsx, src/pages/Dashboard/components/ReportTable/ReportTable.tsx, src/pages/Dashboard/components/ReportTable/TableHeader/TableHeader.tsx, src/pages/Dashboard/components/ReportTable/TableRow/TableRow.tsx, src/services/api/restBuilder/restBuilder.ts, src/services/projection/index.ts, src/services/projection/projections/bench.ts, src/services/projection/projections/needed.ts, src/services/projection/projections/projectionStories/LineChart.tsx, src/services/projection/projections/projectionStories/customProjections.stories.tsx, src/services/projection/projections/projectionStories/projections.stories.tsx, src/services/projection/projections/projections.stories.tsx, src/services/projection/projections/projections.test.ts, src/services/projection/projections/projections.ts, src/services/projection/useProjection.ts, src/services/projection/useTimeline.ts
- staf-238: calculate and display the needed values
- staf-239: calculate and display the bench values
- staf-257: Document use cases in storybook
- staf-82: Details pane accordion
- staf-83: projects are linked
- staf-246: badges and highlighting
=> Dashboard - calculate needed, bench values and document use cases

src/pages/Projects/components/RoleModal/RoleModal.tsx, src/services/api/Assignments/Assignments.ts, src/services/api/Roles/Roles.ts
https://bitovi.atlassian.net/browse/STAF-326
=> allowed for null end date on assignments and roles

src/pages/Projects/components/RoleModal/RoleModal.test.tsx, src/pages/Projects/components/RoleModal/RoleModal.tsx, src/services/helpers/utcdate/index.ts, src/services/helpers/utcdate/utcdate.test.ts, src/services/helpers/utcdate/utcdate.ts
There were a few tests impacted by some of the changes so I needed to update them as well.
=> fix: (STAF-356) update remaining date references and add test for helper

src/pages/Projects/components/RoleCard/RoleCard.tsx, src/pages/Projects/components/RoleModal/RoleModal.tsx, src/services/api/Assignments/Assignments.ts, src/services/projection/projections/projectionStories/projections.stories.tsx
The assignment dates were not properly being saved. I've set them up to be saved properly while converting them to the Date constructor to do math on them.
=> fix: (STAF-346) fix assignment date usage

public/mockServiceWorker.js, src/pages/Dashboard/components/ReportTable/TableRow/TableRow.tsx, src/pages/Employees/Employees.stories.tsx, src/pages/Employees/Employees.tsx, src/pages/Employees/components/EmployeeCard/EmployeeCard.stories.tsx, src/pages/Employees/components/EmployeeCard/EmployeeCard.tsx, src/pages/Employees/components/EmployeeTable/EmployeeTable.test.tsx, src/pages/Employees/components/EmployeeTable/EmployeeTable.tsx, src/pages/Employees/components/EmployeeTable/components/EmployeeTableHeader/EmployeeTableHeader.tsx, src/pages/Employees/components/EmployeeTable/components/EmployeeTableHeader/index.ts, src/pages/Projects/components/RoleCard/RoleCard.tsx, src/services/projection/projections/projectionStories/projections.stories.tsx, src/theme/colors.ts
Adds "current project" with link to project page or "Bench" when no project selected
Changes "roles" to "skills"
Moves skill colors to the theme "colors" object and standardizes its usage within the project
Updates "skills" tab to color coordinate the tabs for skills based on the selected skills
Updates storybook with custom controls
=> Team members current project

src/pages/Dashboard/components/ReportTable/TableRow/TableRow.tsx, src/pages/Projects/Projects/Projects.test.tsx, src/pages/Projects/Projects/Projects.tsx, src/pages/Projects/Projects/components/ProjectCard/ProjectCard.test.tsx, src/pages/Projects/Projects/components/ProjectCard/ProjectCard.tsx, src/pages/Projects/Projects/components/ProjectList/ProjectList.test.tsx, src/pages/Projects/Projects/components/ProjectList/ProjectList.tsx, src/pages/Projects/components/RoleCard/RoleCard.tsx
https://bitovi.atlassian.net/browse/STAF-372
=> Staf 372 add roles to project list page

src/pages/Dashboard/components/ReportTable/TableRow/TableRow.tsx, src/services/projection/projections/bench.ts
Initially confidence values below 50% were filtered, now showing all values over 0%
=> fix: (STAF-363) update partial bench values to display

src/pages/Dashboard/components/ReportTable/TableRow/TableRow.tsx
=> fix: (STAF-314) don't render rows with all 0% needed, don't render cells with 0% needed

src/pages/Projects/components/RoleCard/RoleCard.tsx, src/pages/Skills/Skills.tsx, src/pages/Skills/components/SkillModal/SkillModal.test.tsx, src/pages/Skills/components/SkillModal/SkillModal.tsx, src/pages/Skills/components/SkillModal/index.ts, src/pages/Skills/components/SkillsHeader/SkillsHeader.tsx, src/pages/Skills/components/SkillsTable/SkillsTable.tsx, src/pages/Skills/components/SkillsTable/SkillsTableBody/SkillCard/SkillCard.tsx, src/pages/Skills/components/SkillsTable/SkillsTableBody/SkillsTableBody.tsx
=> Implement add and edit skill modal and functionality (STAF-291) and (STAF-292)

src/pages/Dashboard/components/ReportTable/TableRow/TableRow.tsx
during UAT:
fixed missing row:
other changes still present:
all-0 rows do not show
cells with 0% do not show
=> fix: (STAF-314) hide rows only when all values are 0

src/components/DataTable/DataTimelineHeader/DataTimelineHeader.tsx, src/pages/Dashboard/components/ReportTable/TableHeader/TableHeader.tsx
=> fix: (STAF-412) ensure project table subheader is the same font size as dashboard page

src/pages/Projects/components/RoleModal/RoleModal.test.tsx, src/pages/Projects/components/RoleModal/RoleModal.tsx
https://user-images.githubusercontent.com/13068398/179597908-c0d31c44-6ece-4f54-ba60-afa9d3a85bcd.mov
=> staf-247: only show employees with the right skills for assignments

src/pages/Employees/components/EmployeeTable/EmployeeTable.tsx
the correct query param was missing from the useEmployee hook, adding it resolved the issue.
=> fix: (STAF-387) add query param for useEmployee hook

src/pages/Employees/Employees.test.tsx, src/pages/Employees/components/EmployeeModal/EmployeeModal.test.tsx, src/pages/Employees/components/EmployeeModal/components/EmployeeModalSkillsCard/EmployeeModalSkillsCard.test.tsx, src/pages/Projects/Projects/Projects.test.tsx, src/pages/Projects/components/RoleList/RoleList.test.tsx, src/pages/Skills/Skills.test.tsx, src/pages/Skills/components/SkillModal/SkillModal.test.tsx, src/services/api/Assignments/Assignments.test.tsx, src/services/api/Employees/Employees.test.tsx, src/services/api/Projects/Projects.test.tsx, src/services/api/Roles/Roles.test.tsx, src/services/api/Skills/Skills.test.tsx, src/setupTests.ts
=> load and clear and cleanup in shared test setup instead of everyone individually

src/pages/Projects/Projects/components/ProjectModal/ProjectModal.tsx, src/pages/Projects/components/RoleModal/RoleModal.tsx
- cleaned up last few items that would resolve: https://bitovi.atlassian.net/browse/STAF-79
=> Staf-79 Data Validation

src/pages/Employees/components/EmployeeCard/EmployeeCard.tsx, src/pages/Employees/components/EmployeeModal/EmployeeModal.tsx
https://user-images.githubusercontent.com/13068398/190199961-d50b9b86-9dda-4b5b-bb43-386ac64fb13c.mov
=> staf-287: Team Member Page: Start and End Date Error Handling
